### ISSUE TITLE
Problem downloading many episodes

### ISSUE THREAD

**Issue by quietsy** [akhilrex/podgrab#6] opened 2020-11-08 20:35 UTC
To reproduce:
- Increase "How many episodes to be downloaded when a new podcast is added" to 100 and save
- Add a podcast with many episodes, for example "The Joe Rogan Experience"
- It starts downloading the episodes but then spawns parallel downloads that re-download episodes that have been downloaded already
- The problem gets much worse with more episodes and a longer process

**Comment by akhilrex** [comment] 2020-11-09 00:59
Thanks for reporting this. I think I know what the problem is but it will take some time for me to fix it. In the meanwhile you can do one thing. Recreate the container with environment variable CHECK_FREQUENCY set to some high value like 240. This will make sure that one process finishes before another one begins. 

CHECK_FREQUENCY=240

I will fix this issue and  close this soon.

**Comment by akhilrex** [comment] 2021-01-12 07:12
I have fixed this. Pull the latest image and rebuild.

**Closed by akhilrex** 2021-01-12 07:12 UTC

**Comment by erdoukki** [comment] 2022-03-24 08:11
Trying this...
But a lot of feeds to delete, and to re-add !
not very effective
